### ISSUE TITLE
End waypoints that are pass-through points crash the Full Control Fleet Adapter

### ISSUE THREAD

**Issue by samuelrawrs** [open-rmf/rmf_traffic_editor#429]
In my testing, when given a loop task where the finish_name is also a pass-through point, the full control fleet adapter crashes.

Current RMF version: Latest built from source.
External packages (add to src): [TRL](https://github.com/siot-decada-robotics/trl) 
Ubuntu version: 20.04, ROS2 Galactic

Recreation of bug:
```
ros2 launch trl_demos_gz trl.launch.xml
ros2 run rmf_demos_tasks dispatch_loop -s tinyRobot_2X_spawn -f L2_liftlobby -n 1 --use_sim_time

```
In this case, L2_liftlobby is set as a pass-through point.
You can view the assignments in the trl.building.yaml and/or through traffic-editor.

**Comment by Yadunund** [comment]
This is not the right repository to open this ticket as it relates with the fleet adapter.

With your task, you're asking the robot to arrive at a waypoint and wait there while this waypoint is defined as `passthrough` (which means the robot cannot wait here). Hence, the planner is unable to find a solution. This issue has been discussed previously [here](https://github.com/open-rmf/rmf/discussions/173).

Nonetheless the adapter should not crash but instead go into a failure state. This behavior is fixed as of this PR https://github.com/open-rmf/rmf_ros2/pull/228
