### ISSUE TITLE
Rename Ignition to Gazebo

### ISSUE THREAD

**Issue by ahcorde** [open-rmf/rmf_traffic_editor#449]
[Ignition Gazebo was renamed to Gazebo](https://www.openrobotics.org/blog/2022/4/6/a-new-era-for-gazebo). This project is not still renamed.

Is there any plans to rename it ? Probably `gazebo` should be `gazebo-classic` and `ignition` should be `gazebo`.

**Comment by luca-della-vedova** [comment]
Done in #483
