### ISSUE TITLE
Check returned value of `download_model_fuel_tools` and fail the command if needed

### ISSUE THREAD

**Issue by orensbruli** [open-rmf/rmf_traffic_editor#451]
https://github.com/open-rmf/rmf_traffic_editor/blob/45ce27530dbe661ed456e21a230760707f7acafd/rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py#L159

Currently if any of the downloads of https://github.com/open-rmf/rmf_traffic_editor/blob/45ce27530dbe661ed456e21a230760707f7acafd/rmf_building_map_tools/building_map_model_downloader/building_map_model_downloader.py#L91 fails, no error or messages are returned, so the commands that call this in the workflows does not fail either.

We found some docker images built but with some of the models not been available.

**Comment by aaronchongth** [comment]
While attempting a fix on this, I realized that we have been allowing downloading to fail, precisely because there might be models in other packages that we provide using the gz model paths environment vairable for example in `rmf_demos_assets`. I'm wondering if it might be a better idea to somehow ensure gz doesn't fail if the models do not exist :thinking:

**Comment by orensbruli** [comment]
The problem that brought this to light was that docker images were generated with missing models that were supposed to have been downloaded correctly. If we want to avoid this, I guess we need to make the docker build process fail, but I'm not sure how to get it without getting different exit status if the download fails or succeeds. Maybe we could avoid exiting when the download fails but exit with non 0 status at the end? Some status number that we can check. What do you think?

**Comment by aaronchongth** [comment]
I think I found a solution for it in https://github.com/open-rmf/rmf_traffic_editor/pull/453
