### ISSUE TITLE
Start up error when waypoint's name is pure numbers

### ISSUE THREAD

**Issue by mbb1234567890** [open-rmf/rmf_traffic_editor#462]
## Bug report

Start up rmf_demo error, because of waypoint's name has pure numbers

### Required information:

- Operating system and version:
  - 
  - Ubuntu 20.04
- OpenRMF installation type:
  - 
  - From source
- OpenRMF version or commit hash
  - 
  - c5910c1a Luca Della Vedova <luca@openrobotics.org> on 22-12-6 at 下午2:35
  - committed by GitHub <noreply@github.com>      Unverified GPG signature
- ROS distribution and version:
  - 
  - rolling
- ROS installation type:
  - 
  - binaries
- Package or library, if applicable:
  - 

### Description of the bug

> [fleet_adapter-14] 2023-04-10 17:37:24.539 line526 INFO config_path=/home/bing/rmf_galactic/install/rmf_demos/share/rmf_demos/config/fangshan/harixRobot_config.yaml, nav_graph=/home/bing/rmf_galactic/install/rmf_demos_maps/share/rmf_demos_maps/maps/fangshan/nav_graphs/0.yaml, user_sime_time=False, graph_build_file_path=/home/bing/rmf_galactic/install/rmf_demos_maps/share/rmf_demos_maps/fangshan/fangshan.building.yaml
[building_map_server-3] [INFO] [1681119444.562163742] [building_map_server]: loading map path: /home/bing/rmf_galactic/install/rmf_demos_maps/share/rmf_demos_maps/fangshan/fangshan.building.yaml
[building_map_server-3] [INFO] [1681119444.570400415] [building_map_server]: opening: /home/bing/rmf_galactic/install/rmf_demos_maps/share/rmf_demos_maps/fangshan/fangshan.png
[building_map_server-3] [INFO] [1681119444.571744718] [building_map_server]: read 15945 byte image
[building_map_server-3] Traceback (most recent call last):
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/rmf_building_map_tools/building_map_server", line 11, in <module>
[building_map_server-3]     load_entry_point('rmf-building-map-tools==1.6.0', 'console_scripts', 'building_map_server')()
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 339, in main
[building_map_server-3]     n = BuildingMapServer(map_path)
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 49, in __init__
[building_map_server-3]     self.load_building_yaml(map_path)
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 87, in load_building_yaml
[building_map_server-3]     self.create_map_msg(building)
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 105, in create_map_msg
[building_map_server-3]     self.map_msg.levels.append(self.level_msg(level_data))
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 251, in level_msg
[building_map_server-3]     gn.name = v[2]['name']
[building_map_server-3]   File "/home/bing/rmf_galactic/install/rmf_building_map_msgs/lib/python3.8/site-packages/rmf_building_map_msgs/msg/_graph_node.py", line 173, in name
[building_map_server-3]     assert \
[building_map_server-3] AssertionError: The 'name' field must be of type 'str'

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/10461247/230881853-79a19f5a-736e-4864-a2bd-8e90e3afa56b.png)

### Screenshots

![image](https://user-images.githubusercontent.com/10461247/230881953-c59efacb-f6b7-45eb-87f6-99efe23760b8.png)

**Comment by luca-della-vedova** [comment]
Fixed by #508
