### ISSUE TITLE
[pit crew] Models are downloaded each time when running Gazebo classic simulations

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf_traffic_editor#469]
After building latest `main`, running any `rmf_demos_gz_classic` sim will result in gazebo-11 attempting to download every model each time the simulation is run. Sometimes this takes quite a bit of time. 

Haven't narrowed down the cause of the problem but wonder if changes to the downloaded model path made in [this PR](https://github.com/open-rmf/rmf_traffic_editor/pull/454) may have something to do with it. Esp if gazebo-11 does not check for models from `~/.ignition/fuel/fuel.gazebosim.org`.

**Comment by mxgrey** [comment]
This problem has made gz-classic unusable for me since December of 2022.

IIRC the problem may be related to gz-classic and fuel in some way. I think I was able to replicate the problem using assets unrelated to pitcrew.
