### ISSUE TITLE
Set orientation 

### ISSUE THREAD

**Issue by EmimaJiva** [open-rmf/rmf_traffic_editor#475]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Is there any way to set the orientation with which you want to reach a point?

**Comment by Yadunund** [comment]
Yes, see https://github.com/open-rmf/rmf_traffic_editor/issues/459

Feel free to reopen this ticket if you think your question is unanswered.
