### ISSUE TITLE
[Other issue]:traffic-editor editing the path into straight

### ISSUE THREAD

**Issue by MohammedMuthuFasil** [open-rmf/rmf_traffic_editor#502]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I used the traffic editor to define a path based on points.The points are not straight.So the way is likewise not straight.I've included my picture file for your reference. How do I straighten my path?.
![Screenshot from 2024-08-10 11-22-07](https://github.com/user-attachments/assets/7a6248ae-86b6-4af9-966b-1314fc9ae634)

**Comment by Yadunund** [comment]
Please ask questions like this on our discussions board.

You can make consecutive waypoints collinear by selecting them and clicking `Edit->Align collinear` or simply  pressing`/`.
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/b3c791ff-2fd0-4031-978b-2af982c59320">


It would be great if you could follow up with a pull request to update our [documentation](https://osrf.github.io/ros2multirobotbook/traffic-editor.html) to highlight this feature
