### ISSUE TITLE
How can i get Orange lanes 

### ISSUE THREAD

**Issue by PVijayaGanesh** [open-rmf/rmf_traffic_editor#514]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

How can i get Orange lanes like below image..

![dd](https://github.com/user-attachments/assets/c24d40d5-f7db-4424-9e53-1d1efb6d7211)

please help me..And i saw some *.building.yaml maps without the spawn_robot_type and  spawn_robot_name parameters..

Still they are getting robots on the lanes..how?

**Comment by Yadunund** [comment]
Please ask questions like this on our discussions board in the future.

The traffic lanes for fleets are published by their fleet adapters over the `/nav_graphs` topic. The [rmf_visualization_navgraphs](https://github.com/open-rmf/rmf_visualization/tree/main/rmf_visualization_navgraphs) node then converts the nav graph into a marker message that it publishes and RViz subscribes to.
