### ISSUE TITLE
[Other issue]: How can i decrease lane width in traffic editor...

### ISSUE THREAD

**Issue by pvg6** [open-rmf/rmf_traffic_editor#516]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I want to do openemf in very small place which is 2X3 meters... when i create the map in the traffic editor. the wapoints only occupy the map..

![zoomway](https://github.com/user-attachments/assets/931d3919-f5b4-4a8f-9d9c-cf5b40741a47)

please help me with this...

**Comment by TanJunKiat** [comment]
Hello, this is a visualization preference set in 'rmf_visualization', under the 'rmf_visualization_navgraphs' package. The marker sizes are hardcoded to a specific value at the moment. 

You can tweak the waypoint and lane marker size to a smaller value to make it more readable when running.

**Comment by pvg6** [comment]
@TanJunKiat  Thank you.. solved it..
